---
title: "My title"
subtitle: "My subtitle if needed"
author: 
  - First author
  - Another author
thanks: "Code and data are available at: LINK."
date: today
date-format: long
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false
#| 
library(tidyverse)

```

# Introduction

# Data

## Beyonce 

Which Beyonce song has the highest dancability rating ?

```{r}
#| include: false
#| warning: false
#| message: false

beyonce_data <- readRDS(here::here("data/raw_data/beyonce.rds"))

```


```{r}
#| label: fig-beyonce
#| fig-cap: Dancibility of Beyonce Songs Over Time
#| echo: false

beyonce_data <- as_tibble(beyonce_data)

beyonce_data |>
  filter(album_release_date_precision == "day") |>
  mutate(album_release_date = ymd(album_release_date)) |>
  ggplot(aes(
    x = album_release_date,
    y = danceability,
    group = album_release_date
  )) +
  geom_point(alpha = 0.5) +
  theme_minimal() +
  labs(
    x = "Album release date",
    y = "Average Dancability of Album"
  )
```

```{r}
#| label: tbl-danceability
#| tbl-cap: Dancibility of Beyonce Songs Over Time
#| echo: false

beyonce_data <- as_tibble(beyonce_data)

beyonce_data |>
  filter(album_release_date_precision == "day") |>
  mutate(album_release_date = ymd(album_release_date)) |>
  summarise(avg_danceability = mean(danceability), .by = "album_name") |>
  knitr::kable(
    col.names = c("Album", "Avrage danceability"),
    digits = 3,
    booktabs = TRUE,
    linesep = ""
  )
```

## Fifth Harmony

```{r}
#| include: false
#| warning: false
#| message: false

fifth_data <- readRDS(here::here("data/raw_data/fifth_harmony.rds"))

```


```{r}
#| label: fig-fifth
#| fig-cap: Valence of Fifth Harmony albums over time
#| echo: false

fifth_data <- as_tibble(fifth_data)

fifth_data |>
  filter(album_name %in% c("Reflection", "7/27 (Deluxe)", "Fifth Harmony")) |>
  mutate(album_release_date = ymd(album_release_date)) |>
  filter(album_release_date != "2017-10-29") |>
  ggplot(aes(x = album_name, y = valence)) +
  geom_point(alpha = 0.5) +
  theme_minimal() +
  labs (x = "Album",
        y = "Valence")
```
